/* Generated By:JJTree: Do not edit this line. ASTBaseElement.java */

package edu.uchsc.ccp.opendmap.pattern;

import edu.uchsc.ccp.opendmap.Pattern;

public class ASTBaseElement extends SimpleNode {

	public enum EntryType {
		STRING, REGEX, FRAME_NAME, PATH
	}
	private String image;
	private Pattern.Operator operatorType;
	private EntryType entryType;
  public EntryType getEntryType() {
		return entryType;
	}

	public void setEntryType(EntryType entryType) {
		this.entryType = entryType;
	}

public String getImage() {
	return image;
	}

	public void setImage(String image) {
		if (image == null) {
			this.image = image;
		} else {
			this.image = image.trim();
		}
	}

	public Pattern.Operator getOperatorType() {
		return operatorType;
	}

	public void setOperatorType(Pattern.Operator operatorType) {
		this.operatorType = operatorType;
	}

	public ASTBaseElement(int id) {
    super(id);
  }

  public ASTBaseElement(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
