/* Generated By:JJTree: Do not edit this line. ASTComment.java */

package edu.uchsc.ccp.opendmap.pattern;

public class ASTComment extends SimpleNode {
  public ASTComment(int id) {
    super(id);
  }

  public ASTComment(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
