/* Generated By:JJTree: Do not edit this line. ASTDMAPRuleSet.java */

package edu.uchsc.ccp.opendmap.pattern;


public class ASTDMAPRuleSet extends SimpleNode {
  public ASTDMAPRuleSet(int id) {
    super(id);
  }

  public ASTDMAPRuleSet(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
