/* Generated By:JJTree: Do not edit this line. ASTDMAPRule.java */

package edu.uchsc.ccp.opendmap.pattern;


public class ASTDMAPRule extends SimpleNode {
private String base;
	
	public String getBase() {
		return base;
	}

	public void setBase(String base) {
		if (base == null) {
			this.base = base;
		} else {
			this.base = base.trim();
		}
	}

  public ASTDMAPRule(int id) {
    super(id);
  }

  public ASTDMAPRule(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
