/* Generated By:JJTree: Do not edit this line. ASTEntry.java */

package edu.uchsc.ccp.opendmap.pattern;

import edu.uchsc.ccp.opendmap.Pattern;


public class ASTEntry extends SimpleNode {
	private Pattern.Operator operatorType = Pattern.Operator.SINGLE;

	public Pattern.Operator getOperatorType() {
		return operatorType;
	}

	public void setOperatorType(Pattern.Operator operatorType) {
		this.operatorType = operatorType;
	}

	public ASTEntry(int id) {
    super(id);
  }

  public ASTEntry(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
