/* Generated By:JJTree: Do not edit this line. ASTOperatorEntry.java */

package edu.uchsc.ccp.opendmap.pattern;

public class ASTOperatorEntry extends ASTEntry {
  public ASTOperatorEntry(int id) {
    super(id);
  }

  public ASTOperatorEntry(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
