/* Generated By:JJTree: Do not edit this line. ASTPatterns.java */

package edu.uchsc.ccp.opendmap.pattern;


public class ASTPatterns extends SimpleNode {
  public ASTPatterns(int id) {
    super(id);
  }

  public ASTPatterns(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
