/* Generated By:JJTree: Do not edit this line. ASTPath.java */

package edu.uchsc.ccp.opendmap.pattern;


public class ASTPath extends SimpleNode {
  public ASTPath(int id) {
    super(id);
  }

  public ASTPath(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
