/* Generated By:JJTree: Do not edit this line. ASTPattern.java */

package edu.uchsc.ccp.opendmap.pattern;


public class ASTPattern extends SimpleNode {
  public ASTPattern(int id) {
    super(id);
  }

  public ASTPattern(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
