/* Generated By:JJTree: Do not edit this line. ASTPatternComponent.java */

package edu.uchsc.ccp.opendmap.pattern;

public class ASTPatternComponent extends SimpleNode {
  public ASTPatternComponent(int id) {
    super(id);
  }

  public ASTPatternComponent(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
