/* Generated By:JJTree: Do not edit this line. ASTSimpleEntry.java */

package edu.uchsc.ccp.opendmap.pattern;

public class ASTSimpleEntry extends ASTEntry {
  public ASTSimpleEntry(int id) {
    super(id);
  }

  public ASTSimpleEntry(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
