/* Generated By:JJTree: Do not edit this line. ASTSlotName.java */

package edu.uchsc.ccp.opendmap.pattern;


public class ASTSlotName extends SimpleNode {
	private String name;
 
	public String getName() {
		return name;
	}

	public void setName(String name) {
		if (name == null) {
			this.name = name;
		} else {
			this.name = name.trim();
		}
	}

 public ASTSlotName(int id) {
    super(id);
  }

  public ASTSlotName(DMAPPatternParser p, int id) {
    super(p, id);
  }

}
