/* Generated By:JJTree: Do not edit this line. DMAPPatternParserTreeConstants.java */

package edu.uchsc.ccp.opendmap.pattern;

public interface DMAPPatternParserTreeConstants
{
  public int JJTDMAPRULESET = 0;
  public int JJTCOMMENT = 1;
  public int JJTDMAPRULE = 2;
  public int JJTPATTERNS = 3;
  public int JJTPATTERN = 4;
  public int JJTPATTERNCOMPONENT = 5;
  public int JJTENTRY = 6;
  public int JJTOPERATORENTRY = 7;
  public int JJTSIMPLEENTRY = 8;
  public int JJTBASEELEMENT = 9;
  public int JJTSLOTNAME = 10;
  public int JJTPATH = 11;


  public String[] jjtNodeName = {
    "DMAPRuleSet",
    "Comment",
    "DMAPRule",
    "Patterns",
    "Pattern",
    "PatternComponent",
    "Entry",
    "OperatorEntry",
    "SimpleEntry",
    "BaseElement",
    "SlotName",
    "Path",
  };
}
