/* Generated By:JJTree&JavaCC: Do not edit this line. DMAPPatternParserConstants.java */
package edu.uchsc.ccp.opendmap.pattern;

public interface DMAPPatternParserConstants {

  int EOF = 0;
  int REGEX1 = 6;
  int REGEX2 = 7;
  int SYMBOL = 8;
  int FRAME_NAME = 9;
  int STRING1 = 10;
  int STRING2 = 11;
  int LETTER = 12;
  int DIGIT = 13;
  int COMMENT = 14;
  int LBRACKET = 15;
  int RBRACKET = 16;
  int SEMICOLON = 17;
  int ARROW = 18;
  int COMMA = 19;
  int LPAREN = 20;
  int RPAREN = 21;
  int CLAUSE = 22;
  int KLEENE_STAR = 23;
  int KLEENE_PLUS = 24;
  int ALTERNATION = 25;
  int OPTIONAL = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<REGEX1>",
    "<REGEX2>",
    "<SYMBOL>",
    "<FRAME_NAME>",
    "<STRING1>",
    "<STRING2>",
    "<LETTER>",
    "<DIGIT>",
    "<COMMENT>",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "\"*\"",
    "\"+\"",
    "\"|\"",
    "\"?\"",
  };

}
